title: "Kodachrome: An Exploration of Light"
menu:
  - about: "About"
  - first_gallery: "Different ways to layer light unto a sensor for images we share with each other's hearts."
  - http://twitter.com: "siraf"
