title: "Kodachrome"
sub_title: "Adventures in exploring a chemical medium of visual capture"
share: true
license:
  name: "Attribution-NonCommercial-NoDerivatives"
  url: "https://creativecommons.org/licenses/by-nc-nd/4.0/"
settings:
  gm:
    quality: 80
  light_mode: true
  og: true

